### ISSUE TITLE
Consider upstreaming in btcwallet

### ISSUE THREAD

**Issue by kargakis** [OpenBazaar/spvwallet#6]
It seems that you are heavy btcsuite users which is great. It would be nice to see the work in this repo upstreamed in [btcwallet](https://github.com/btcsuite/btcwallet/issues/219).

**Comment by cpacia** [comment]
It would be nice if we could just use btcwallet instead of rolling our own. Though at least 75% of this code relies on btcd as it is. The difference is it just maintains it's own header database for spv and custom transaction database.

Some of which is kind of custom to OpenBazaar... for example, we need to add watch scripts to the db to listen for transactions coming in and going out of multisig scripts. 

But if we could do that in btcwallet, that would be nice.

**Comment by hoffmabc** [comment]
@cpacia is this a non-fix for now? or do we actually plan on trying to meet this request?

**Comment by kargakis** [comment]
Likely superseded by https://github.com/decred/dcrwallet/issues/1000
